# Generated by Django 4.2.6 on 2023-11-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_advertising'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sneakers',
            new_name='Krosofkalar',
        ),
    ]
