# Generated by Django 4.2.6 on 2023-11-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_rename_sneakers_krosofkalar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Kategoriyalar',
        ),
    ]
