# Generated by Django 4.2.6 on 2023-11-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0006_rename_category_kategoriyalar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buy',
            new_name='Sotib_olinganlar',
        ),
    ]
