# Generated by Django 4.2.6 on 2023-11-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_rename_buy_sotib_olinganlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='krosofkalar',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
